baseURL = "https://niiazov.com/"
defaultContentLanguage = "ru"
languageCode = "ru"

title = "Сайт Ришата Ниязова"

theme = "gokarna"

# Автоматически генерировать robots.txt
enableRobotsTXT = true

[params]
  # URL-адрес аватара на главной странице
  avatarURL = "https://avatars.githubusercontent.com/u/96833766?v=4"
  #avatarURL = "/images/avatar.jpeg"

  # Choose one of size-xs, size-s, size-m, size-l & size-xl. (Default: size-m)
  avatarSize = ""

  # Описание для отображения на главной странице
  description = "Добро пожаловать в мой уголок интернета! Здесь я делюсь своими мыслями, переживаниями и увлечениями. От путешествий по вселенной до глупостей, которые приходят в мою голову — каждый пост отражает мою жизнь и то, что меня вдохновляет. Присоединяйтесь ко мне в этом увлекательном путешествии!"

  # Цвет акцента отображается при наведении курсора на теги <a>.
  accentColor = "#4dc1ff"

  # Отображать кнопку «Вернуться наверх» в сообщениях
  ShowBackToTopButton = true

  # Вы можете использовать это для внедрения любого HTML в тег <head>.
  # Идеальный вариант использования — импортировать собственный js/css или добавить фрагмент аналитики.
  customHeadHTML = ""

  # Ключевые слова, релевантные для SEO
  metaKeywords = ["blog", "gokarna", "hugo"]

  # Если вы хотите отображать сообщения на главной странице, доступны следующие варианты:
  # "popular" (order posts by weight), "recent" (order posts by date)
  # or "" (do not display, default option)
  showPostsOnHomePage = "recent"

  # Текст нижнего колонтитула
  footer = "Ришат Ниязов"
  
  socialIcons = [
    {name = "linkedin", url = "https://www.linkedin.com/in/niiazov/"},
    {name = "x", url = "https://x.com/DxCpp"},
    {name = "mastodon", url = "https://c.im/@rishat"},
    {name = "youtube", url = "https://www.youtube.com/@niiazov/"},
    {name = "github", url = "https://github.com/DxCpp"},
    {name = "email", url = "mailto:rishat@niiazov.com"}
  ]

  dateFormat = "2 January, 2006"

  customCommentHTML = """
  <!-- Google Tag Manager -->
  <script>(function(w,d,s,l,i){w[l]=w[l]||[];w[l].push({'gtm.start':
  new Date().getTime(),event:'gtm.js'});var f=d.getElementsByTagName(s)[0],
  j=d.createElement(s),dl=l!='dataLayer'?'&l='+l:'';j.async=true;j.src=
  'https://www.googletagmanager.com/gtm.js?id='+i+dl;f.parentNode.insertBefore(j,f);
  })(window,document,'script','dataLayer','GTM-T3QRR6H9');</script>
  <!-- End Google Tag Manager -->
  <!-- Google Tag Manager (noscript) -->
  <noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-T3QRR6H9"
  height="0" width="0" style="display:none;visibility:hidden"></iframe></noscript>
  <!-- End Google Tag Manager (noscript) -->
  """


[menu]
    [[menu.main]]
    # Уникальный идентификатор пункта меню.
    identifier = "home"

    url = "/"
    pre = "<span data-feather='home'></span>"
    post = ""
    name = "Главная"
    weight = 1

  [[menu.main]]
    # Уникальный идентификатор пункта меню.
    identifier = "posts"
    url = "/posts/"
    # Перед именем можно добавить дополнительную информацию (поддерживается формат HTML), например значки.
    pre = "<span data-feather='book'></span>"

    # После имени можно добавить дополнительную информацию (поддерживается формат HTML), например значки.
    post = ""

    # Отображаемое имя
    name = "Блог"

    # Порядок
    weight = 2


  [[menu.main]]
    # Unique identifier for a menu item
    identifier = "projects"
    url = "/projects/"
    # You can add extra information before the name (HTML format is supported), such as icons
    pre = "<span data-feather='terminal'></span>"

    # You can add extra information after the name (HTML format is supported), such as icons
    post = ""

    # Display name
    name = "Проекты"

    # Weights are used to determine the ordering
    weight = 3

  [[menu.main]]
    identifier = "tags"
    name = "Теги"
    url = "/tags/"
    weight = 4

    pre = "<span data-feather='tag'></span>"
    
#  [[menu.main]]
#    identifier = "github"
#    name = "GitHub"
#    url = "https://github.com/DxCpp"
#    weight = 5
#    
#    # We use feather-icons: https://feathericons.com/
#    pre = "<span data-feather='github'></span>"